<a href="https://colab.research.google.com/github/Padmasriariveni/Hangman-game/blob/main/numpy_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import math
print(math.e)

2.718281828459045


In [3]:
a=10
def area_of_square(side):
  return side**2
print(f"Area of the square:",area_of_square(10))
def calculator(x,y):
  print("Addition is:",x+y)
  print("Subtraction is:",x-y)
  print("Multiplication is:",x*y)
  print("Division is:",x/y)
calculator(50,90)

Area of the square: 100
Addition is: 140
Subtraction is: -40
Multiplication is: 4500
Division is: 0.5555555555555556


In [4]:
import numpy as np


Let us now compare the time that cpu takes to run a list and numpy

In [5]:
from time import process_time
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.001218112999999743


In [6]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0003770689999997856


Numpy Arrays

In [7]:
list1=[1,2,3,4,5]#the data will displayes in square brackets and sep by ","
print(list1)
type(list1) #if we see we get the type as list

[1, 2, 3, 4, 5]


list

In [8]:
np_array=np.array([1,2,3,4,5])#displays without","
print(np_array)
type(np_array)#it belongs to n dimension array as it similar to matrix

[1 2 3 4 5]


numpy.ndarray

creating 1 d array

In [9]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [10]:
a.shape

(5,)

In [11]:
b=np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
b.shape

(2, 5)

In [12]:
c=np.array([(1.5,2,3,4),(6,7,8,9)],dtype=float)
print(c) #to get in desired data type use dtype

[[1.5 2.  3.  4. ]
 [6.  7.  8.  9. ]]


Initial placeholders in numpy arrays

In [14]:
#lets create a numpy arrays of zeros
x=np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
#lets create an arrays of ones
y=np.ones([5,5])
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
#array of a specific value
z=np.full((3,3),6)
print(z)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [17]:
#create an identity matrix
a=np.eye(4)
print(a) #all the diagonal values equal to 1

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
#create numpy array with random values
b=np.random.random((4,2))
print(b) #all the values between 0 and 1


[[0.27767007 0.57608959]
 [0.06313799 0.6404871 ]
 [0.39256353 0.18353204]
 [0.12536126 0.05936463]]


In [20]:
#random integer values within a specific range
c=np.random.randint(10,150,(3,5))
print(c)

[[ 46  15  76  26 120]
 [ 59  39  92  82  14]
 [103  39 119  14 125]]


In [25]:
 #creating an array of evenly spaced values
 d=np.linspace(10,50,6)# 10 and 50 is the range
 #6 is specifying the number of vales required
 print(d)

[10. 18. 26. 34. 42. 50.]


In [26]:
#array of evenlt spaced values
e=np.arange(10,30,6)
print(e)

[10 16 22 28]


In [28]:
#convert a list to a numpy array
list2=[10,20,30,40,50]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [29]:
tup1=[10,20,30,40,50]
np_array=np.asarray(tup1)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray


Analysing a numpy array

In [38]:
c=np.random.randint(10,90,(2,3,1))
print(c)

[[[11]
  [28]
  [26]]

 [[68]
  [15]
  [65]]]


In [33]:
#array dimensions
print(c.shape)

(5, 5)


In [37]:
print(c.ndim) #number of dimensions

3


In [40]:
print(c.size) #number of elements in an array

6


In [41]:
#checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on np array

In [45]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2) #concatenates both the strings

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [47]:
a=np.random.randint(0,10,(2,2))
b=np.random.randint(0,20,(2,2))
print(a)
print(b)

[[0 5]
 [4 5]]
[[12 12]
 [ 1  9]]
[[12 17]
 [ 5 14]]


In [50]:
print(a+b)
print(a/b)
print(a-b)
print(a*b)

[[12 17]
 [ 5 14]]
[[0.         0.41666667]
 [4.         0.55555556]]
[[-12  -7]
 [  3  -4]]
[[ 0 60]
 [ 4 45]]


In [52]:
a=np.random.randint(0,10,(2,2))#we will have different values for a and b
b=np.random.randint(0,20,(2,2))
print(a)
print(b)

[[2 8]
 [6 4]]
[[13 11]
 [ 9 18]]


In [54]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 19]
 [15 22]]
[[-11  -3]
 [ -3 -14]]
[[26 88]
 [54 72]]
[[0.15384615 0.72727273]
 [0.66666667 0.22222222]]


ARRAY MANIPULATION

In [55]:
array=np.random.randint(0,10,(2,2))
print(array)
print(array.shape)

[[9 3]
 [0 8]]
(2, 2)


In [56]:
#transpose
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[9 0]
 [3 8]]
(2, 2)


In [57]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[9 0]
 [3 8]]
(2, 2)


In [62]:
#reshaping an array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 4]
 [9 6]]
(2, 2)


In [72]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])  # Total elements = 6
b = a.reshape(3, 2)  # 3 rows, 2 columns
print(b)
print(b.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
''